### ISSUE TITLE
Node 14 Issue

### ISSUE THREAD

**Issue by timothyerwin** [willmendesneto/hex-to-css-filter#18] opened 2021-09-01 19:18 UTC
This doesn't seem to work with the latest Node version...I can't downgrade to 6 or whatever just to make one package work which seems to be the instructions on this repo.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hex-to-css-filter@5.1.0 postinstall: `husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hex-to-css-filter@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Not sure if there is any other workaround?

**Comment by willmendesneto** [comment] 2021-09-15 15:39
Hi @timothyerwin 

I'm looking into that! I'll share the updates here as soon as I get into the cause and troubleshooting

**Comment by willmendesneto** [comment] 2021-09-16 23:06
Good news: the issue is solved on the latest version 🎉

Please upgrade your project to use `hex-to-css-filter@5.2.0` and enjoy!

Closing this issue for now. Once again, thanks @timothyerwin  for raising that!

**Closed** 2021-09-16 23:06 UTC
